version: '3.1'
services:
  db:
    image: postgres:16.0-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: &us db_user
      POSTGRES_PASSWORD: *us
      POSTGRES_DB: default
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
volumes:
  db-data:
